# AI-Challenge
* weight yolov3-ssp.pt : https://drive.google.com/file/d/1qoCRv6Yw-LWdxCiWCEHmMCPGwfR7R0Gn/view?usp=sharing
* error : path in file utils.py (    path = "/media/thorpham/PROJECT/AIC_2020_Challenge_Track-1/thor/yolov3_detect_car/yolov3/data/coco.names")  line 58 ; anyone help me fix .
